char getPfCh(int x, int y);
void setupDsScreen();
void replace(char a, char b);
void swap(char a, char b);
char* getStString();
int getBestLevel();
void setBestLevel(int level);
void clearBestLevel();
void load();
void copyA(char** to, char** from);
void frameLoop();
void doFrame1();
void doFrame8();
bool isEnemy(char x);
bool canfall(char x);
bool conveys(char x);
bool probe(int x, int y, char ch);
void die();
void win();
void pollInput();
void checkKeyPressed();
void checkKeyReleased();
int getDsScreenCoordinates();